project:
  type: book

book:
  title: "CASA0023_Learning_Diary_ZYH"
  author: "Jane Doe"
  date: "02/02/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

